### ISSUE TITLE
circle CI broken

### ISSUE THREAD

**Issue by masterfloda** [AltSchool/dynamic-rest#182]
circle CI fails on Dependencies > pyenv local 2.7.10 3.3.3 3.4.3 3.5.0 with `pyenv: version '3.3.3' not installed` (same goes for 3.5.0 if you fix that). Has there been some change on Circle CI?

This can be fixed by installing the versions before using them. Also, I would suggest testing the newest versions of Py2 and Py3.

This circle.yml works, though I think we could omit some of these versions to speed up the build:

```yaml
dependencies:
    override:
        - pip install -r requirements.txt
        - python setup.py develop
        - pyenv install -s 2.7.13
        - pyenv install -s 3.3.3
        - pyenv install -s 3.4.3
        - pyenv install -s 3.5.0
        - pyenv install -s 3.6.1
        - pyenv local 2.7.13 3.3.3 3.4.3 3.5.0 3.6.1

test:
    override:
        - ENABLE_INTEGRATION_TESTS=True py.test tests/integration
        - tox
```
